export const cards = [
  {
    id: 1,
    name: "Shadow Wraith",
    image: "src/assets/cards/front_card_320x480_1.png",
    isFlipped: false,
    isMatched: false,
  },
  {
    id: 2,
    name: "Blood Moon",
    image: "src/assets/cards/front_card_320x480_2.png",
    isFlipped: false,
    isMatched: false,
  },
  {
    id: 3,
    name: "Cursed Relic",
    image: "src/assets/cards/front_card_320x480_3.png",
    isFlipped: false,
    isMatched: false,
  },
  {
    id: 4,
    name: "Spectral Chains",
    image: "src/assets/cards/front_card_320x480_4.png",
    isFlipped: false,
    isMatched: false,
  },
  {
    id: 5,
    name: "Soul Devourer",
    image: "src/assets/cards/front_card_320x480_5.png",
    isFlipped: false,
    isMatched: false,
  },
  {
    id: 6,
    name: "Bone Whisperer",
    image: "src/assets/cards/front_card_320x480_6.png",
    isFlipped: false,
    isMatched: false,
  },
  {
    id: 7,
    name: "Cryptic Tomb",
    image: "src/assets/cards/front_card_320x480_7.png",
    isFlipped: false,
    isMatched: false,
  },
  {
    id: 8,
    name: "Void Phantom",
    image: "src/assets/cards/front_card_320x480_8.png",
    isFlipped: false,
    isMatched: false,
  },
  {
    id: 9,
    name: "Void",
    image: "src/assets/cards/front_card_320x480_9.png",
    isFlipped: false,
    isMatched: false,
  },
];
